### ISSUE TITLE
Home assistant integration

### ISSUE THREAD

**Issue by ProLoser** [d8ahazard/HueDream#12]
What are your thoughts on integration with home assistant? Something like adding this as a plug-in to my existing home assistant setup and leveraging the integrations already developed for home assistant or at the very least the docker environment

**Comment by d8ahazard** [comment]
In a nutshell, it's probably not going to happen.

For starters, my app is written in c# because of the significant speed
boost gained from using a compiled language. If I port it back to python,
I'm either going to lose performance, device compatibility, or
cross-platform functionality.

Second, I'm not sure if the things I'm doing are even *possible* with the
support libs HA has. For example, Hue Entertainment streaming requires an
encrypted UDP protocol, and the libs to support it are few and far between.
Plus, my app needs to be able to blast data at ~60fps, and potentially
access a webcam, microphone, or other peripheral device.

Last - I eventually intend on creating a dedicated device this can be run
on with it's own HDMI capture, so doing all the work to make it a plugin
for something else doesn't make a lot of sense to me.

Sorry!

**Comment by ProLoser** [comment]
Gotcha, thanks for taking the time to explain.
