### ISSUE TITLE
(Xiaomi) Yeelight Support

### ISSUE THREAD

**Issue by Steke93** [d8ahazard/HueDream#3]
Hi, 
i'm really into HueDream but don't have Phillips Hue but Yeelights.
How about to support this? 

Okay, the Name "**Hue**Dream" where not suitable anymore however I and many other would love it.

BR
Steven

**Comment by d8ahazard** [comment]
So, I checked this out. It'd take a few things.

1. 1 or more Yeelights to work with to develop the software. 
2. Motivation. Like...donations. It's Xmas season, my time is finite, and this is a lot of work. ;)
3. Some hacking. I looked at the docs for Yeelight, and the discovery and control stuff would all be simple enough to figure out. 

But, the issue comes in with the fact that unlike Hue, Yeelight doesn't seem to support a "streaming" or entertainment API like Hue lights do.

With hue, I contact the main controller, say, "I'm gonna start blasting data at you for lights x, y, and z", and then just start UDP sending the data over the network at 10s of FPS.

With Yeelight, they only accept normal TCP commands...which means multiple TCP requests per second per light. It's not impossible, but would require some more "stuff" to make sure that stuff doesn't get congested...

**Comment by Steke93** [comment]
Hi, 

thanks for your statement.
May I will buy some Hue Bulbs, but without bridge, I want to use IoBrooker and a Zigbee Adapter. 
Let me send you some "Motivation" (via PayPal) . I'm not sure i will use your Work soon, but I will thank you for the work. ;)

**Comment by d8ahazard** [comment]
I humbly accept donations via paypal at donate.to.digitalhigh@gmail.com. ;)
