### ISSUE TITLE
Version update failing

### ISSUE THREAD

**Issue by MikeMannina** [d8ahazard/HueDream#38]
The latest update isn't being applied for some reason.  It recognizes the tag change but not any file updates.

Here are the log messages:

20:16:45 DBG][SystemUtil][Update] No updates are required at this time.
[20:16:45 DBG][SystemUtil][Update] Tag is 1.2.5 versus 1.2.4.0
[20:16:45 DBG][SystemUtil][Update] Release fetched...

**Comment by d8ahazard** [comment]
Hey Mike. 

Sorry about this, tried moving the "check version" bits from a script to the app itself, realized I borked the version check (still).

I've done two things to deal with this:

One, updated the check logic to use the dotnet Version class, which should make the checks work even with disparate point versions, like 1.2.5 versus 1.2.4.0.

The other is that after installing 1.2.5, I added a "force" mechanism to the routine triggered by the UI so that if you click the "Update" button from settings twice in a 30-second period, updates will be installed regardless of tag comparisons.


`
sudo su


wget -qO- https://raw.githubusercontent.com/d8ahazard/glimmr/master/src/Glimmr/script/update_linux.sh | bash
`

**Comment by MikeMannina** [comment]
I'm getting the following error when trying to execute that command.

su: invalid option -- 'q'
Try 'su --help' for more information.

**Comment by Nachobizniz** [comment]
2 commands

Sudo Su  (you will need to type password again)

Then the

wget -qO- https://raw.githubusercontent.com/d8ahazard/glimmr/master/src/Glimmr/script/update_linux.sh | bash

Best Regards,
Greg Fletcher


On Mar 15, 2022, at 1:28 AM, MikeMannina ***@***.***> wrote:

﻿
I'm getting the following error when trying to execute that command.

su: invalid option -- 'q'
Try 'su --help' for more information.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by d8ahazard** [comment]
Sorry, just realized Github hosed my code/comment.

As Greg said, should be two commands. I usually type the:

sudo su

First, enter the pass...then copy the WHOLE line with the wget bit, then right-click to paste it, press enter.

That'll fetch the latest update script and run it, which will in turn fetch the latest release, stop glimmr, install it, and restart glimmr.

**Comment by MikeMannina** [comment]
Thanks!  Could be how I logged in, but I didn't need the first line.  The update worked with just wget so I'm not going to look a gift horse... lol
