### ISSUE TITLE
MacOS install

### ISSUE THREAD

**Issue by Endlessknight** [d8ahazard/HueDream#9]
Could you provide an install guide on how to install this helpful software on macOS?
The downloadable zip for macOS is full of files but nothing I found can be used so far

**Comment by d8ahazard** [comment]
I've since started providing a MacOS installer package in most (but not all) releases. The package will install Glimmr as a service to /Library/Glimmr (I think) that will auto-start with the computer. I need to add a better mechanism for controlling the service, but it's at least a start. Once running, you can just open up http://localhost or http://127.0.0.1 in a browser to access the UI.
